### ISSUE TITLE
Cog unable to be added through Red's downloader cog

### ISSUE THREAD

**Issue by palmtree5** [TrainerDex/TrainerDex-RedCog#4]
If you want people to be able to install this cog through Red's downloader cog, you should add a file called `info.json` in the root directory of the repository (see the [documentation](http://twentysix26.github.io/Red-Docs/red_cog_info_json/#repository-infojson) for what should be in that file)

**Comment by JayTurnr** [comment]
Cog is not ready for public consumption yet

**Comment by JayTurnr** [comment]
Would just like to give an update to this: It's currently dependent on a library, which will soon be submitted to PyPi, once submitted and approved, I can make this available via red's downloader cog. However, I'm not sure if it will be approved, as it requires an API key for a service I've created? I imagine there's a rule against that. Oh well, I'll try 😄

**Comment by JayTurnr** [comment]
It is now downloadable via the downloader cog. 
`[p]cog repo add trainerdex https://github.com/TrainerDex/TrainerDex-RedCog.git`
`[p]cog install trainerdex`

Although set up requires a little.. training.
Which is fine because people have to get an API key from me anyway.


@palmtree5 can I just ask how you found this cog anyway?
